apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress-ng
  template:
    metadata:
      labels:
        app: stress-ng
    spec:
      containers:
      - name: stress-ng
        image: docker.io/nikhithavaddempudi/stress-ng:latest
        args:
        - "--cpu"
        - "1"  # Stress 1 CPU per pod
        - "--cpu-load"
        - "41"  # Stress 80% of the CPU per worker
        - "--timeout"
        - "3600s"  # Run for exactly 1 hour
        resources:
          requests:
            cpu: "2"  # Request 2 CPUs per pod (this will simulate ~82% of a 5-CPU node across 2 pods)
          limits:
            cpu: "2"  # Limit the pod's CPU usage to 2 CPUs
      nodeSelector:
        kubernetes.io/hostname: minikube-m02  # Target the specific node
      restartPolicy: Always  # Pods will be restarted after 1 hour
