# Service Account Definition
apiVersion: v1
kind: ServiceAccount
metadata:
  name: disasterrecovery-operator-sa
  namespace: default

---
# Cluster Role Definition
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disasterrecovery-operator-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
      - persistentvolumes
      - persistentvolumeclaims
      - configmaps
    verbs: ["get", "list", "create", "update", "delete","watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs: ["get", "list", "create", "update", "delete","watch"]

  - apiGroups: ["example.com"]
    resources:
      - disasterrecoveries
    verbs: ["get", "list", "create", "update", "delete","watch"]

---
# Cluster Role Binding Definition
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: disasterrecovery-operator-binding
subjects:
  - kind: ServiceAccount
    name: disasterrecovery-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: disasterrecovery-operator-role
  apiGroup: rbac.authorization.k8s.io

---
# Custom Resource Definition (CRD) for DisasterRecovery
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: disasterrecoveries.example.com
spec:
  group: example.com
  names:
    kind: DisasterRecovery
    plural: disasterrecoveries
    singular: disasterrecovery
    shortNames:
      - dr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nodeName:
                  type: string
                backupConfigMap:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Completed
                    - Failed
