apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-request-deployment
spec:
  replicas: 4  # Number of pods
  selector:
    matchLabels:
      app: memory-request-app
  template:
    metadata:
      labels:
        app: memory-request-app
    spec:
      containers:
      - name: memory-request-container
        image: docker.io/library/nginx:latest 
        resources:
          requests:
            memory: "1736Mi"  # Memory request is set to (1.7GiB)
          limits:
            memory: "1736Mi"  

