name: Build with Docker, Deploy with Minikube (Podman)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted  # This must be your machine with Docker, Podman, and Minikube

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image with Docker
      run: |
        IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Minikube (Podman runtime) with kubectl
      run: |
        IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:latest

        # Check if deployment exists
        if kubectl get deployment myapp-deployment > /dev/null 2>&1; then
          echo "Updating deployment image..."
          kubectl set image deployment/myapp-deployment myapp=$IMAGE --record
        else
          echo "Creating new deployment..."
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: myapp-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: myapp
            template:
              metadata:
                labels:
                  app: myapp
              spec:
                containers:
                - name: myapp
                  image: $IMAGE
                  ports:
                  - containerPort: 80
          EOF
        fi

        kubectl rollout status deployment/myapp-deployment

