name: Build, Push, and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted  # <-- this tells GitHub to use your laptop

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        podman build -t docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:latest .
        podman push docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Deploy to Minikube
      run: |
        kubectl set image deployment/myapp-deployment myapp=docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:latest --record || \
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/myapp-deployment

