name: Build, Push, and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted  # Run on your own machine with Podman and Minikube

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image with Podman
      run: |
        IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:latest
        podman build -t $IMAGE .
        podman push $IMAGE

    - name: Deploy to Minikube with kubectl
      run: |
        IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:latest

        # If the deployment exists, update the image. If not, create it.
        if kubectl get deployment myapp-deployment > /dev/null 2>&1; then
          echo "Updating existing deployment..."
          kubectl set image deployment/myapp-deployment myapp=$IMAGE --record
        else
          echo "Creating new deployment..."
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: myapp-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: myapp
            template:
              metadata:
                labels:
                  app: myapp
              spec:
                containers:
                  - name: myapp
                    image: $IMAGE
                    ports:
                      - containerPort: 80
          EOF
        fi

        kubectl rollout status deployment/myapp-deployment

