name: Build, Push, and Deploy Frontend & Backend to Minikube
on:
  push:
    branches:
      - main

jobs:
  build_push_deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Podman
      run: |
        if ! command -v podman &> /dev/null; then
          echo "Podman is not installed. Installing Podman..."
          brew install podman
        fi

    - name: Build and push frontend image
      run: |
        IMAGE_NAME="docker.io/${{ secrets.DOCKER_USERNAME }}/frontend:final"
        podman build -t $IMAGE_NAME ./frontend
        podman push $IMAGE_NAME

    - name: Build and push backend image
      run: |
        IMAGE_NAME="docker.io/${{ secrets.DOCKER_USERNAME }}/backend:final"
        podman build -t $IMAGE_NAME ./backend
        podman push $IMAGE_NAME

    - name: Ensure Minikube cluster (3 nodes)
      run: |
        if ! minikube status &> /dev/null; then
          echo "Starting Minikube cluster with 3 nodes..."
          minikube start --nodes=3 --driver=podman --container-runtime=cri-o --cni=bridge
        else
          echo "Minikube cluster already running."
        fi

    - name: Set up kubectl context
      run: kubectl config use-context minikube

    - name: Apply all Kubernetes manifests
      run: |
        find ./manifests -name '*.yaml' -exec kubectl apply -f {} \;

    - name: Run all Python scripts in parallel with separate terminals
      run: |
        for script in $(find ./scripts -name '*.py'); do
          echo "Starting $script in a new terminal..."
          osascript -e "tell app \"Terminal\" to do script \"python3 $script\""
        done

