name: Build and Push Image with Podman

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the `main` branch

jobs:
  build_and_push:
    runs-on: self-hosted  # This must be your machine with Podman installed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the image using Podman
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/myapp:latest"  # Name your image (e.g., myapp)
        podman build -t $IMAGE_NAME .

    - name: Push the image to Docker Hub using Podman
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/myapp:latest"  # Ensure proper naming
        podman push $IMAGE_NAME

